version: '2.3'
services:
  db:
    image: mysql:latest
    volumes:
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=codetestdb
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=password
    ports:
    - 3306:3306
  web:
    image: mortgageplan
    # Command makes it that web container will not launch before database is ready
    command: bash -c "while !</dev/tcp/db/3306; do sleep 5; done; java -jar mortgageplan-docker.jar"
    depends_on:
      - db
    ports:
    - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=codetest
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=codetestdb
      - DATABASE_PORT=3306