version: '3.7'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
    - 3306:3306
  web:
    image: mortgageplan
    # Command makes it that web container will not launch before database is ready
    command: bash -c "while !</dev/tcp/db/3306; do sleep 5; done; java -jar mortgageplan-docker.jar"
    depends_on:
      - db
    ports:
    - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=test
      - DATABASE_PASSWORD=test
      - DATABASE_NAME=test
      - DATABASE_PORT=3306